### ISSUE TITLE
Rubymotion app using 3rd-party pod crashes in uilabel.rb

### ISSUE THREAD

**Issue by cotsog** [rubymotion/sugarcube#172]
Hi,

I'm a developer from SupportKit (an iOS framework: http://supportkit.io) and one of our client is trying to integrate us along with sugarcube in Rubymotion. Unfortunately, his app crashes. I investigated and it seems like the crash occurs when we do [UiLabel new] but only while being in applicationDidFinishLaunching: in the SupportKit framework. I have a sample project here that reproduces the crash:

https://github.com/cotsog/motionkit

When I change all [UILabel new] in SupportKit for [[UILabel alloc] init] the crash does not happen anymore.

Do you think you can have a look?

Let me know if you need more information.

Thanks!

**Comment by otzy007** [comment]
Hi,

The app is crashing for me too while trying to use sugarcube with [RWDropdownMenu] (https://github.com/eternityz/RWDropdownMenu).
But if I do app.files.delete_if { |f| f.include? 'sugarcube-factories/uilabel.rb' } it's no longer crashing.
RWDropDownMenu it's using UILabel.new.

Here's an example app: https://github.com/otzy007/RWDRopDown-sugarcube-bug

**Comment by colinta** [comment]
OK, well I think it would be appropriate to just remove these `new` wrappers, they are too volatile.  I hate breaking changes, but I think it's appropriate here.

**Comment by colinta** [comment]
Removed in 3.3.0.  I'll email the list about this change!  I renamed the methods to `UILabel.label` and `NSError.error`.  From now on, we'll avoid overwriting `new`.  Thanks!

**Comment by colinta** [comment]
Shoot, kinda screwed that one up, pushed fixes in 3.3.1 (`UILabel.label` was calling `super()` instead of `new()`)

**Comment by otzy007** [comment]
Great. Now everything it's fine. Thank you :+1:
