### ISSUE TITLE
Crash in REPL

### ISSUE THREAD

**Issue by mikz** [rubymotion/sugarcube#187]
Hi there.

If I require 'sugarcube/repl' in my project then after few seconds I get following:

```
2015-02-08 11:03:28.644 GoodNightHue[10550:165946] repl.rb:213:in `check_sugarcube_view': no view has been assigned to SugarCube::Repl::adjust (RuntimeError)
	from repl.rb:60:in `origin:'
	from kernel.rb:86:in `origin:'
```

I'd love to provide more information, but no idea what is needed.

**Comment by mikz** [comment]
When I remove the REPL, there is underlying exception thrown from BW::Reactor. So that is the culprit.
But still, repl masks that exception for its own.

**Comment by colinta** [comment]
I've tried a bunch of ways to "trap" this, but so far I haven't come up with a way to show the error other than removing `sugarcube-repl` and running the code again.

**Comment by dchersey** [comment]
Is there any update on this issue?  It happens for me every time I open a ProMotion TableScreen.

**Comment by colinta** [comment]
Nope, I still don't have a workaround.

**Comment by dchersey** [comment]
Thanks — bummer!

David

**Comment by ewilliam** [comment]
ran into the same error when opening a PM::TableScreen. sad cuz i liked the stonger REPL
