### ISSUE TITLE
NSDate.delta exception when only using sugarcube-nsdate (v3.3.1)

### ISSUE THREAD

**Issue by jjnevis** [rubymotion/sugarcube#190]
When I only include the sugarcube-nsdate (v3.3.1) package I get the following exception:

    nsdate_delta.rb:22:in `delta:': undefined method `minutes' for 0:Fixnum

I don't get this exception if I include all packages (for v3.3.1) or use v1.6.3 (see example gemfile lines below)

    gem 'sugarcube', '3.3.1', :require => 'sugarcube-classic' # does not error
    gem 'sugarcube', '1.6.3', :require => ['sugarcube', 'sugarcube-nsdate'] # does not error
    gem 'sugarcube', '3.3.1', :require => ['sugarcube', 'sugarcube-nsdate'] # DOES error

**Comment by colinta** [comment]
Thanks!  It's relying on the `numbers` package.  I'll remove that dependency.

**Comment by jjnevis** [comment]
Ah, cool - that was quick!

**Comment by colinta** [comment]
Yeah I don't like to leave work undone!  Available in 3.3.2.

**Comment by jjnevis** [comment]
Thanks, that's working great now.
