### ISSUE TITLE
NSArray NSColor

### ISSUE THREAD

**Issue by bmichotte** [rubymotion/sugarcube#195]
Hi @colinta, is there any reason why https://github.com/rubymotion/sugarcube/blob/master/lib/osx/sugarcube-color/nsarray.rb define uicolor instead of nscolor ? 

Looks like strange to use uicolor on osx (while the rest of the class are about nscolor)

**Comment by colinta** [comment]
Oh no that's probably a mistake. I'll take a look.

**Comment by colinta** [comment]
Easy fix!  0f1225007

Please PR in the future, I can always use the help.
