### ISSUE TITLE
undefined method `nscolor' for :white:Symbol

### ISSUE THREAD

**Issue by superplussed** [rubymotion/sugarcube#197]
I have sugarcube included in my Gemfile like so:

```
gem 'sugarcube', require: [
	'sugarcube-ui',
	'sugarcube-repl'
]
```

And I can verify that I have the repl correctly loaded by running the "tree" command and seeing output.  But in my button_style method, I get the above error for code that looks like:

```
class MainWindowLayout < MK::WindowLayout
    ...
    def button_style
        title 'Press it!'
        size_to_fit
        background_color :white.nscolor
     end
```

The .nscolor method is taken from the docs, so I'm not sure what the issue is.  Any ideas?

**Comment by colinta** [comment]
That's dev strange! I'll try this tonight when I get home

**Comment by colinta** [comment]
Oh right, the color additions are in the `sugarcube-color` package.

The `sweet-kit` gem is a good reference for what files to include:

###### [lib/sweet-kit.rb](https://github.com/motion-kit/sweet-kit/blob/master/lib/sweet-kit.rb)

```ruby
require 'sugarcube'
require 'sugarcube-ui'
require 'sugarcube-color'
require 'sugarcube-constants'
```
