### ISSUE TITLE
swipe guesture not working with webViewScreen

### ISSUE THREAD

**Issue by poc7667** [rubymotion/sugarcube#208]
swipe guesture not working with webViewScreen

I'm not sure what's the problem,

But it just doesn't work.

I running on the iOS 8.2 simulator

# Rakefile

  require 'sugarcube-gestures'

# Webview

  class WebScreen < PM::WebScreen
    attr_accessor :url
    status_bar :none

    def on_load
      test_if_login
      set_nav_bar_button :left, title: "Back", action: :go_back
      view.on_swipe :left do
        go_back
      end
    end

    def go_back
      if webview.canGoBack
        PM.logger.debug "go back"
        webview.goBack
      end
    end
  end

**Comment by colinta** [comment]
Have you tried to add a swipe gesture manually, to see if it's a compatibility issue with `UIWebView` and `UISwipeGestureRecognizer`?

**Comment by poc7667** [comment]
I will try that, thanks :)
