### ISSUE TITLE
Repl `tree` command not showing correct outline on macOS...

### ISSUE THREAD

**Issue by digitalmoksha** [rubymotion/sugarcube#212]
When using the REPL command `tree`, it usually gives the outline of the main window (by default).  Currently running on Sierra and RM 4.14, instead it only shows a single window with no views

```
(main)> tree
  0: . #<NSWindow:0x101b7c8c0>

=> #<NSWindow:0x101b7c8c0>
```

It seems to stem from the `SugarCube::Repl.window` command (`lib/osx/sugarcube-repl/repl.rb`) that tries to grab a default window

```
          NSApplication.sharedApplication.keyWindow ||
          NSApplication.sharedApplication.mainWindow ||
          NSApplication.sharedApplication.windows[0]
```

` NSApplication.sharedApplication.windows` shows that there are two elements, and in this case, it is the second one that contains the main window.  Not sure how to fix this, since according to the docs the order of `windows` is undetermined, and `keyWindow` / `mainWindow` can be nil if the app is in the background (which it is when typing in the repl.

The `tree` command does take an index, so you can do `tree 1` to access what, in my case, is the main window, so there is a workaround...

**Comment by colinta** [comment]
Thanks for the heads up!  An easy fix, I think, would be to filter for `window.subviews.count > 0`, and return *that* window.

**Comment by colinta** [comment]
I've pushed a patch for this, can you install from github and see if that fixes it?

**Comment by colinta** [comment]
Oh, shoot, I was looking at iOS.  OSX, got it - one sec.
